<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Veterna Home Gutenverse Help', 'veterna' ),
	'categories' => array( 'veterna-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1150"},"gap":"no","elementId":"guten-G6LfAR","margin":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"50","bottom":"100"}},"Tablet":{"unit":"px","dimension":{"top":"40","right":"20","bottom":"80","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"30","right":"20","bottom":"80","left":"20"}}}} -->
<div class="section-wrapper" data-id="G6LfAR"><section class="wp-block-gutenverse-section guten-element guten-section guten-G6LfAR layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100},"elementId":"guten-mO4MzQ","order":{"Desktop":"1","Tablet":1},"verticalAlign":{"Desktop":"center"},"margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"left":"10","right":"60"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"40","left":"0"}},"Mobile":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-mO4MzQ"><div class="guten-column-wrapper" data-id="mO4MzQ"><!-- wp:gutenverse/advanced-heading {"elementId":"guten-MWYjX1","alignText":{"Desktop":"flex-start"},"text":"","focusText":"Let\'s Help Us","subText":"Our Fundraising For Animal Welfare","showLine":"none","lineMargin":{"Desktop":[]},"mainMargin":{"Desktop":[]},"mainPadding":{"Desktop":[]},"focusColor":{"type":"variable","id":"theme-3"},"focusTypography":{"type":"variable","id":"ywYJC3","font":{"label":"Quicksand","value":"Quicksand","type":"google"},"size":{"Desktop":{"point":"20","unit":"px"},"Tablet":{"point":"19","unit":"px"},"Mobile":{"point":"18","unit":"px"}},"weight":"700"},"focusMargin":{"Desktop":[]},"focusPadding":{"Desktop":[]},"subColor":{"type":"variable","id":"theme-0"},"subTypography":{"type":"variable","id":"mG7K1R","font":{"label":"Quicksand","value":"Quicksand","type":"google"},"size":{"Desktop":{"point":"48","unit":"px"},"Tablet":{"point":"45","unit":"px"},"Mobile":{"point":"40","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"700"},"subMargin":{"Desktop":[]},"subPadding":{"Desktop":{"unit":"px","dimension":{"top":"20"}}},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"positioningType":{"Tablet":"custom"},"positioningWidth":{"Tablet":{"point":"649","unit":"px"}}} -->
<div class="guten-element guten-advanced-heading guten-MWYjX1"><div class="heading-section "><h2 class="heading-title"><span class="heading-title"></span><span class="heading-focus">Let\'s Help Us</span></h2></div><span class="heading-subtitle">Our Fundraising For Animal Welfare</span></div>
<!-- /wp:gutenverse/advanced-heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-B448e4","alignment":{"Desktop":"left"},"textColor":{"type":"variable","id":"theme-2"},"typography":{"type":"variable","id":"7MBQTH","font":{"label":"Quicksand","value":"Quicksand","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"15","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"unit":"em","point":"1.5"}}},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"30"}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":null},"positioningType":{"Desktop":"custom","Tablet":"full"},"positioningWidth":{"Desktop":{"point":"490","unit":"px"}}} -->
<div class="guten-element gutenverse-text-editor guten-B448e4"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusm tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam quis nostrud exercitation ullamco.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/heading {"elementId":"guten-uRRKrM","color":{"type":"variable","id":"theme-0"},"typography":{"type":"variable","id":"YlLg3o","font":{"label":"Quicksand","value":"Quicksand","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"17","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"weight":"700"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"20","top":"0"}}}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-uRRKrM">Opening Hours</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/section {"layout":"fullwidth","isChild":true,"gap":"no","elementId":"guten-phUu62","border":{"radius":{"Desktop":[]},"top":{"type":"solid","width":1,"color":{"r":234,"g":234,"b":234,"a":1}},"bottom":{"width":1,"type":"solid","color":{"r":234,"g":234,"b":234,"a":1}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"0","bottom":"10","left":"0"}}}} -->
<div class="section-wrapper" data-id="phUu62"><section class="wp-block-gutenverse-section guten-element guten-section guten-phUu62 layout-fullwidth align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":50},"elementId":"guten-QNGPze"} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-QNGPze"><div class="guten-column-wrapper" data-id="QNGPze"><!-- wp:gutenverse/heading {"elementId":"guten-ikHNLa","color":{"type":"variable","id":"theme-0"},"typography":{"type":"variable","id":"5gQi4O","font":{"label":"Quicksand","value":"Quicksand","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"15","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"500"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-ikHNLa">Monday - Saturday</h2>
<!-- /wp:gutenverse/heading --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":50},"elementId":"guten-wyhUCj"} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-wyhUCj"><div class="guten-column-wrapper" data-id="wyhUCj"><!-- wp:gutenverse/heading {"elementId":"guten-gWd1cd","textAlign":{"Desktop":"right"},"color":{"type":"variable","id":"theme-0"},"typography":{"type":"variable","id":"7MBQTH","font":{"label":"Quicksand","value":"Quicksand","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"15","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"unit":"em","point":"1.5"}}},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-gWd1cd">08.00 AM - 19.00 PM</h2>
<!-- /wp:gutenverse/heading --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"layout":"fullwidth","isChild":true,"gap":"no","elementId":"guten-cgLU18","border":{"radius":{"Desktop":[]},"bottom":{"width":1,"type":"solid","color":{"r":234,"g":234,"b":234,"a":1}}},"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"10","bottom":"10"}}}} -->
<div class="section-wrapper" data-id="cgLU18"><section class="wp-block-gutenverse-section guten-element guten-section guten-cgLU18 layout-fullwidth align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":50},"elementId":"guten-sYid7K"} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-sYid7K"><div class="guten-column-wrapper" data-id="sYid7K"><!-- wp:gutenverse/heading {"elementId":"guten-MfClMy","color":{"type":"variable","id":"theme-0"},"typography":{"type":"variable","id":"5gQi4O","font":{"label":"Quicksand","value":"Quicksand","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"15","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"500"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-MfClMy">Sunday</h2>
<!-- /wp:gutenverse/heading --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":50},"elementId":"guten-19Hver"} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-19Hver"><div class="guten-column-wrapper" data-id="19Hver"><!-- wp:gutenverse/heading {"elementId":"guten-RS6oCo","textAlign":{"Desktop":"right"},"color":{"type":"variable","id":"theme-3"},"typography":{"type":"variable","id":"7MBQTH","font":{"label":"Quicksand","value":"Quicksand","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"15","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"unit":"em","point":"1.5"}}},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-RS6oCo">Closed</h2>
<!-- /wp:gutenverse/heading --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"layout":"fullwidth","isChild":true,"gap":"no","elementId":"guten-zwcknH","margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"30"}}}} -->
<div class="section-wrapper" data-id="zwcknH"><section class="wp-block-gutenverse-section guten-element guten-section guten-zwcknH layout-fullwidth align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50},"elementId":"guten-mQwRYb","margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":"15"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-mQwRYb"><div class="guten-column-wrapper" data-id="mQwRYb"><!-- wp:gutenverse/heading {"elementId":"guten-W1zPrb","color":{"type":"variable","id":"theme-0"},"typography":{"type":"variable","id":"YlLg3o","font":{"label":"Quicksand","value":"Quicksand","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"17","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"weight":"700"},"containsAnchorTag":false,"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":""}}}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-W1zPrb">Denpasar, Bali</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/icon-list {"elementId":"guten-jvgfqs","spaceBetween":{"Desktop":"10"},"iconColor":{"type":"variable","id":"theme-3"},"iconSize":{"Desktop":"14"},"textColor":{"type":"variable","id":"theme-2"},"textIndent":{"Desktop":"10"},"textTypography":{"type":"variable","id":"7MBQTH","font":{"label":"Quicksand","value":"Quicksand","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"15","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"unit":"em","point":"1.5"}}}} -->
<div class="guten-element guten-icon-list guten-jvgfqs"><div class=" list-wrapper "><!-- wp:gutenverse/icon-list-item {"elementId":"guten-y9iMi1"} -->
<div class="guten-element guten-icon-list-item guten-y9iMi1"><div class="list-divider"></div><a id="guten-y9iMi1"><i class="fas fa-map-marker-alt"></i><span class="list-text ">Jl. Niti Mandala No.190, Bali</span></a></div>
<!-- /wp:gutenverse/icon-list-item -->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-sHIAZz"} -->
<div class="guten-element guten-icon-list-item guten-sHIAZz"><div class="list-divider"></div><a id="guten-sHIAZz"><i class="fas fa-phone"></i><span class="list-text ">(+62) 8152 254 239</span></a></div>
<!-- /wp:gutenverse/icon-list-item -->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-hhZAvX"} -->
<div class="guten-element guten-icon-list-item guten-hhZAvX"><div class="list-divider"></div><a id="guten-hhZAvX"><i class="fas fa-envelope"></i><span class="list-text ">contact@domain.com</span></a></div>
<!-- /wp:gutenverse/icon-list-item --></div></div>
<!-- /wp:gutenverse/icon-list --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":null},"elementId":"guten-GeIokJ","margin":{"Desktop":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"left":"15"}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-GeIokJ"><div class="guten-column-wrapper" data-id="GeIokJ"><!-- wp:gutenverse/heading {"elementId":"guten-Bv8KWE","color":{"type":"variable","id":"theme-0"},"typography":{"type":"variable","id":"YlLg3o","font":{"label":"Quicksand","value":"Quicksand","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"17","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"weight":"700"},"containsAnchorTag":false,"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":""}}}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-Bv8KWE">Kuta, Bali</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/icon-list {"elementId":"guten-5WQRrn","spaceBetween":{"Desktop":"10"},"iconColor":{"type":"variable","id":"theme-3"},"iconSize":{"Desktop":"14"},"textColor":{"type":"variable","id":"theme-2"},"textIndent":{"Desktop":"10"},"textTypography":{"type":"variable","id":"7MBQTH","font":{"label":"Quicksand","value":"Quicksand","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"15","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"unit":"em","point":"1.5"}}},"border":{"radius":{"Desktop":[]}}} -->
<div class="guten-element guten-icon-list guten-5WQRrn"><div class=" list-wrapper "><!-- wp:gutenverse/icon-list-item {"elementId":"guten-uBfI21"} -->
<div class="guten-element guten-icon-list-item guten-uBfI21"><div class="list-divider"></div><a id="guten-uBfI21"><i class="fas fa-map-marker-alt"></i><span class="list-text ">Jl. Sunset Road No.815, Bali</span></a></div>
<!-- /wp:gutenverse/icon-list-item -->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-mUJSWy"} -->
<div class="guten-element guten-icon-list-item guten-mUJSWy"><div class="list-divider"></div><a id="guten-mUJSWy"><i class="fas fa-phone"></i><span class="list-text ">(+62) 8152 254 239</span></a></div>
<!-- /wp:gutenverse/icon-list-item -->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-FoJMeZ"} -->
<div class="guten-element guten-icon-list-item guten-FoJMeZ"><div class="list-divider"></div><a id="guten-FoJMeZ"><i class="fas fa-envelope"></i><span class="list-text ">contact@domain.com</span></a></div>
<!-- /wp:gutenverse/icon-list-item --></div></div>
<!-- /wp:gutenverse/icon-list --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100,"Mobile":null},"elementId":"guten-MWNW5B","order":{"Desktop":"1","Tablet":2},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}}},"boxShadow":{"color":{"r":0,"g":0,"b":0,"a":0.1},"horizontal":"0","vertical":"0","blur":"10","spread":"0","position":"outline"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"0","top":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"40","bottom":"40","left":"40"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"40","left":"30"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-MWNW5B"><div class="guten-column-wrapper" data-id="MWNW5B"><!-- wp:gutenverse/heading {"elementId":"guten-6mt4qx","color":{"type":"variable","id":"theme-0"},"typography":{"type":"variable","id":"FhoQio","font":{"label":"Quicksand","value":"Quicksand","type":"google"},"size":{"Desktop":{"point":"26","unit":"px"},"Tablet":{"point":"24","unit":"px"},"Mobile":{"point":"22","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":""}},"weight":"700"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-6mt4qx">Donations Form</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/form-builder {"elementId":"guten-lxnNNz","formId":{"label":"Form Donations Veterna","value":287}} -->
<form style="display:none" class="guten-element guten-form-builder guten-lxnNNz" data-form-id="287"><!-- wp:gutenverse/section {"layout":"fullwidth","isChild":true,"gap":"no","elementId":"guten-aLLv8D","border":{"radius":{"Desktop":[]}},"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"10"}}}} -->
<div class="section-wrapper" data-id="aLLv8D"><section class="wp-block-gutenverse-section guten-element guten-section guten-aLLv8D layout-fullwidth align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":null},"elementId":"guten-Ehcl7r","margin":{"Desktop":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":"10"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-Ehcl7r"><div class="guten-column-wrapper" data-id="Ehcl7r"><!-- wp:gutenverse/form-input-text {"elementId":"guten-t8OmnF","showLabel":false,"inputLabel":"Name","inputPlaceholder":"Your Name","inputName":"your-name","showHelper":false,"labelColor":{"Desktop":[]},"labelPadding":{"Desktop":{"unit":"px","dimension":{"bottom":"0","right":"0","left":"0","top":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"labelMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"17","right":"25","bottom":"17","left":"25"}},"Tablet":{"unit":"px","dimension":{"top":"15.75","bottom":"15.75","right":"25","left":"25"}},"Mobile":{"unit":"px","dimension":{"top":"15.75","right":"25","bottom":"15.75","left":"25"}}},"inputMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"placeholderColor":{"Desktop":{"type":"variable","id":"theme-2"}},"inputTypography":{"type":"variable","id":"7MBQTH","font":{"label":"Quicksand","value":"Quicksand","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"15","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"unit":"em","point":"1.5"}}},"inputColorNormal":{"Desktop":{"type":"variable","id":"theme-0"}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"theme-1"}}},"inputBorderNormalResponsive":{"Tablet":{"radius":[]},"Mobile":{"radius":[]}},"inputBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}},"all":{"color":{"type":"variable","id":"theme-2"},"width":1,"type":"solid"}},"inputColorFocus":{"Desktop":{"type":"variable","id":"theme-0"}},"inputBorderFocus":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"theme-2"}}},"inputBgColorNormal":{"Desktop":{"r":249,"g":249,"b":249,"a":1}}} -->
<div class="guten-element guten-form-input-text guten-form-input guten-input-position-top guten-t8OmnF hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;text&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="Your Name" name="your-name" class="gutenverse-input gutenverse-input-text" type="text"/><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-text --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":null},"elementId":"guten-Lmv3tp","margin":{"Desktop":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-Lmv3tp"><div class="guten-column-wrapper" data-id="Lmv3tp"><!-- wp:gutenverse/form-input-telp {"elementId":"guten-2NQJzn","showLabel":false,"showHelper":false,"labelColor":{"Desktop":[]},"labelPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"labelMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"0","top":"0","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"helperPadding":{"Mobile":[]},"margin":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"inputLabel":"Phone Number","inputPlaceholder":"Phone Number","inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"17","right":"20","bottom":"17","left":"20"}},"Tablet":{"unit":"px","dimension":{"top":"15.75","bottom":"15.75","right":"25","left":"25"}},"Mobile":{"unit":"px","dimension":{"top":"15.75","bottom":"15.75","right":"25","left":"25"}}},"inputMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"placeholderColor":{"Desktop":{"type":"variable","id":"theme-2"}},"inputTypography":{"type":"variable","id":"7MBQTH","font":{"label":"Quicksand","value":"Quicksand","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"15","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"unit":"em","point":"1.5"}}},"inputColorNormal":{"Desktop":{"type":"variable","id":"theme-0"}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"theme-1"}}},"inputBorderNormalResponsive":{"Tablet":{"radius":[]},"Mobile":{"radius":[]}},"inputBorderHover":{"radius":{"Desktop":[]},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"2YSiuc"}}},"inputColorFocus":{"Desktop":{"type":"variable","id":"8fesXU"}},"inputBorderFocus":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"2YSiuc"}}},"inputBgColorNormal":{"Desktop":{"r":249,"g":249,"b":249,"a":1}}} -->
<div class="guten-element guten-form-input-telp guten-form-input guten-input-position-top guten-2NQJzn hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;telp&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="Phone Number" name="input-phone" class="gutenverse-input gutenverse-input-tel" type="tel" pattern="\+[0-9]+[0-9\s\-]*"/><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-telp --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"layout":"fullwidth","isChild":true,"gap":"no","elementId":"guten-1ZENPQ","border":{"radius":{"Desktop":[]}},"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":""}}}} -->
<div class="section-wrapper" data-id="1ZENPQ"><section class="wp-block-gutenverse-section guten-element guten-section guten-1ZENPQ layout-fullwidth align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":null},"elementId":"guten-NTUlPn","margin":{"Desktop":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":"10"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-NTUlPn"><div class="guten-column-wrapper" data-id="NTUlPn"><!-- wp:gutenverse/form-input-email {"elementId":"guten-4hx65p","showLabel":false,"showHelper":false,"labelColor":{"Desktop":[]},"labelPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"labelMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"0","top":"0","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"inputPlaceholder":"Your Email","inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"17","right":"20","bottom":"17","left":"20"}},"Tablet":{"unit":"px","dimension":{"top":"15.75","bottom":"15.75","right":"25","left":"25"}},"Mobile":{"unit":"px","dimension":{"top":"15.75","bottom":"15.75","right":"25","left":"25"}}},"inputMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"placeholderColor":{"Desktop":{"type":"variable","id":"theme-2"}},"inputTypography":{"type":"variable","id":"7MBQTH","font":{"label":"Quicksand","value":"Quicksand","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"15","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"unit":"em","point":"1.5"}}},"inputColorNormal":{"Desktop":{"type":"variable","id":"theme-0"}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"theme-1"}}},"inputBorderNormalResponsive":{"Tablet":{"radius":[]},"Mobile":{"radius":[]}},"inputBorderHover":{"radius":{"Desktop":[]},"all":{"width":1,"type":"solid","color":{"type":"variable","id":"2YSiuc"}}},"inputColorFocus":{"Desktop":{"type":"variable","id":"theme-0"}},"inputBorderFocus":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"theme-2"}}},"inputBgColorNormal":{"Desktop":{"r":249,"g":249,"b":249,"a":1}}} -->
<div class="guten-element guten-form-input-email guten-form-input guten-input-position-top guten-4hx65p hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;email&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="Your Email" name="input-email" class="gutenverse-input gutenverse-input-email" type="email"/><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-email --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":null},"elementId":"guten-1r7Yqd","margin":{"Desktop":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-1r7Yqd"><div class="guten-column-wrapper" data-id="1r7Yqd"><!-- wp:gutenverse/form-input-number {"elementId":"guten-u161FI","showLabel":false,"showHelper":false,"labelPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"labelMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"inputPlaceholder":"Amount : $","inputPadding":{"Desktop":{"unit":"px","dimension":{"right":"20","left":"20","top":"17","bottom":"17"}},"Tablet":{"unit":"px","dimension":{"top":"15.75","bottom":"15.75","right":"25","left":"25"}},"Mobile":{"unit":"px","dimension":{"top":"15.75","bottom":"15.75","right":"25","left":"25"}}},"inputMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"placeholderColor":{"Desktop":{"type":"variable","id":"theme-2"}},"inputTypography":{"type":"variable","id":"7MBQTH","font":{"label":"Quicksand","value":"Quicksand","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"15","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"unit":"em","point":"1.5"}}},"inputColorNormal":{"Desktop":{"type":"variable","id":"theme-0"}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"theme-1"}}},"inputBorderNormalResponsive":{"Tablet":{"radius":[]},"Mobile":{"radius":[]}},"inputBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}},"all":{"color":{"type":"variable","id":"theme-2"},"width":1,"type":"solid"}},"inputBgColorNormal":{"Desktop":{"r":249,"g":249,"b":249,"a":1}}} -->
<div class="guten-element guten-form-input-number guten-form-input guten-input-position-top guten-u161FI hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;number&quot;,&quot;required&quot;:false,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="Amount : $" name="input-number" class="gutenverse-input gutenverse-input-number" type="number" min="0" max="100" step="1"/><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-number --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/form-input-select {"elementId":"guten-0erfrY","showLabel":false,"inputPlaceholder":"Donation To","showHelper":false,"labelPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"labelMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"helperPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[]},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"selectOptions":[{"value":"option-1","label":"Abandoned Dog\'s In Cage","_key":"oM5iei"},{"value":"option-2","label":"Homeless Street Cat","_key":"gFcNWg"},{"value":"option-3","label":"Animal Shelter Homes","_key":"2JiPci"}],"inputPadding":{"Desktop":{"unit":"px","dimension":{"right":"20","left":"20","top":"17","bottom":"17"}},"Tablet":{"unit":"px","dimension":{"top":"15.11","bottom":"15.11","right":"25","left":"25"}},"Mobile":{"unit":"px","dimension":{"top":"15.75","right":"25","bottom":"15.75","left":"25"}}},"inputMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"placeholderColor":{"Desktop":{"type":"variable","id":"theme-2"}},"placeholderBgColor":{"Desktop":{"r":249,"g":249,"b":249,"a":1}},"inputTypography":{"type":"variable","id":"7MBQTH","font":{"label":"Quicksand","value":"Quicksand","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"15","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"unit":"em","point":"1.5"}}},"inputColorNormal":{"Desktop":{"type":"variable","id":"theme-0"}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}},"all":{"width":1,"type":"solid","color":{"type":"variable","id":"theme-1"}}},"inputBorderNormalResponsive":{"Tablet":{"radius":[]},"Mobile":{"radius":[]}},"inputColorHover":{"Desktop":{"type":"variable","id":"theme-2"}},"inputBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"theme-2"}}},"choicesColorNormal":{"Desktop":{"type":"variable","id":"theme-2"}},"choicesColorHover":{"Desktop":{"type":"variable","id":"theme-0"}}} -->
<div class="guten-element guten-form-input-select guten-form-input guten-input-position-top guten-0erfrY hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><select name="input-select" data-validation="{&quot;type&quot;:&quot;select&quot;,&quot;required&quot;:false,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" class="gutenverse-input gutenverse-input-select"><option value="">Donation To</option><option value="option-1">Abandoned Dog\'s In Cage</option><option value="option-2">Homeless Street Cat</option><option value="option-3">Animal Shelter Homes</option></select><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-select -->

<!-- wp:gutenverse/form-input-textarea {"elementId":"guten-8rX8wd","showLabel":false,"showHelper":false,"labelColor":{"Desktop":{"type":"variable","id":"8fesXU"}},"labelTypography":{"type":"variable","id":"aBflyL","font":{"label":"Barlow","value":"Barlow","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"600","lineHeight":{"Desktop":{"unit":"em","point":"1.2"}}},"labelPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"labelMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"0","top":"0","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"helperPadding":{"Desktop":[]},"margin":{"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"inputHeight":{"Desktop":"150"},"inputLabel":"Message","inputPlaceholder":"Your Message","inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"17","right":"20","bottom":"17","left":"20"}},"Tablet":{"unit":"px","dimension":{"top":"15.75","bottom":"15.75","right":"25","left":"25"}},"Mobile":{"unit":"px","dimension":{"top":"15.75","bottom":"15.75","right":"25","left":"25"}}},"inputMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"placeholderColor":{"Desktop":{"type":"variable","id":"theme-2"}},"inputTypography":{"type":"variable","id":"7MBQTH","font":{"label":"Quicksand","value":"Quicksand","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"15","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"unit":"em","point":"1.5"}}},"inputColorNormal":{"Desktop":{"type":"variable","id":"theme-0"}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"theme-1"}}},"inputBorderNormalResponsive":{"Tablet":{"radius":[]},"Mobile":{"radius":[]}},"inputBorderHover":{"radius":{"Desktop":[]},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"theme-2"}}},"inputColorFocus":{"Desktop":{"type":"variable","id":"theme-0"}},"inputBorderFocus":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"theme-2"}}},"inputBgColorNormal":{"Desktop":{"r":249,"g":249,"b":249,"a":1}}} -->
<div class="guten-element guten-form-input-textarea guten-form-input guten-input-position-top guten-8rX8wd hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><textarea data-validation="{&quot;type&quot;:&quot;textarea&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="Your Message" name="input-textarea" class="gutenverse-input gutenverse-input-text"></textarea><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-textarea -->

<!-- wp:gutenverse/form-input-submit {"elementId":"guten-89RFcw","content":"Donate Now","buttonWidth":{"Desktop":"100"},"buttonBackground":{"type":"default","color":{"type":"variable","id":"theme-3"}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"theme-6"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}}},"margin":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"20"}}},"color":{"type":"variable","id":"theme-4"},"typography":{"type":"variable","id":"YtKk3z","font":{"label":"Quicksand","value":"Quicksand","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"15","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"700","lineHeight":{"Desktop":{"unit":"em","point":"1.5"}}},"hoverTextColor":{"type":"variable","id":"theme-3"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"18","bottom":"18","right":"45","left":"45"}},"Mobile":{"unit":"px","dimension":{"top":"17.5","bottom":"17.5"}},"Tablet":{"unit":"px","dimension":{"top":"16.75","right":"35","bottom":"16.75","left":"35"}}}} -->
<div class="guten-element guten-button-wrapper guten-submit-wrapper guten-89RFcw"><div class="form-notification"></div><button class="guten-button gutenverse-input-submit guten-button-sm" type="submit"><span>Donate Now</span></button><div class="gutenverse-input-submit-loader"><i class="fas fa-spinner fa-spin"></i></div></div>
<!-- /wp:gutenverse/form-input-submit --></form>
<!-- /wp:gutenverse/form-builder --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
	'images'      => '',
	'is_sync' => true,
);
