<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Veterna 404 Gutenverse Hero', 'veterna' ),
	'categories' => array( 'veterna-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"height":{"Desktop":{"unit":"vh","point":"100"}},"gap":"no","elementId":"guten-1KkyWv","heightControl":"fit","align":"middle","verticalAlign":"center","overflow":"hidden","background":{"videoPlayOnMobile":false,"type":"default","image":{"Desktop":{"id":945,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/eror-page.webp"}},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"}},"backgroundOverlay":{"type":"default","color":{"r":16,"g":16,"b":16,"a":1}},"opacity":"0.75","margin":{"Desktop":[],"Mobile":[],"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"bottom":"20","right":"20","left":"20"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} -->
<div class="section-wrapper" data-id="1KkyWv"><section class="wp-block-gutenverse-section guten-element guten-section guten-1KkyWv layout-boxed align-middle overflow-hidden"><div class="guten-background-overlay"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"sectionVerticalAlign":"center","elementId":"guten-DiFUj9","verticalAlign":{"Desktop":"center"},"horizontalAlign":{"Desktop":"center"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"","left":""}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":""}},"Tablet":{"unit":"px","dimension":{"top":"","right":"20","bottom":"","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"0","bottom":"","right":"0","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-DiFUj9"><div class="guten-column-wrapper" data-id="DiFUj9"><!-- wp:gutenverse/advanced-heading {"elementId":"guten-K3dZWG","alignText":{"Desktop":"center"},"titleTag":"h1","text":"","focusText":"404","subText":"Page Not Found","showLine":"none","lineMargin":{"Desktop":[]},"mainMargin":{"Desktop":[]},"mainPadding":{"Desktop":[]},"focusColor":{"type":"variable","id":"theme-4"},"focusTypography":{"type":"variable","id":"ZOrjjL","font":{"label":"Quicksand","value":"Quicksand","type":"google"},"size":{"Desktop":{"point":"130","unit":"px"},"Tablet":{"point":"110","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":""},"Tablet":{"unit":"em","point":""}},"weight":"700"},"focusMargin":{"Desktop":[],"Tablet":[]},"focusPadding":{"Desktop":[],"Tablet":[]},"subColor":{"type":"variable","id":"theme-4"},"subTypography":{"type":"variable","id":"mG7K1R","font":{"label":"Quicksand","value":"Quicksand","type":"google"},"size":{"Desktop":{"point":"48","unit":"px"},"Tablet":{"point":"45","unit":"px"},"Mobile":{"point":"40","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"700"},"subMargin":{"Desktop":[],"Mobile":[],"Tablet":[]},"subPadding":{"Desktop":[],"Mobile":[],"Tablet":[]},"margin":{"Tablet":[],"Desktop":[]},"padding":{"Tablet":[],"Desktop":[]}} -->
<div class="guten-element guten-advanced-heading guten-K3dZWG"><div class="heading-section "><h1 class="heading-title"><span class="heading-title"></span><span class="heading-focus">404</span></h1></div><span class="heading-subtitle">Page Not Found</span></div>
<!-- /wp:gutenverse/advanced-heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-T649Pb","alignment":{"Desktop":"center"},"textColor":{"type":"variable","id":"theme-4"},"typography":{"type":"variable","id":"7MBQTH","font":{"label":"Quicksand","value":"Quicksand","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"15","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"unit":"em","point":"1.5"}}},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"20","bottom":"30"}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"%","dimension":{"right":"22","left":"22"}},"Tablet":{"unit":"%","dimension":{"right":"20","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="guten-element gutenverse-text-editor guten-T649Pb"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/button {"elementId":"guten-pdbPzf","content":"Back To Home","paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"18.5","bottom":"18.5","right":"35","left":"35"}},"Tablet":{"unit":"px","dimension":{"top":"17.25","right":"35","bottom":"17.25","left":"35"}},"Mobile":{"unit":"px","dimension":{"top":"18","bottom":"18"}}},"buttonBackground":{"type":"default","color":{"type":"variable","id":"theme-3"}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"theme-6"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":""}},"Mobile":{"unit":"px","dimension":{"bottom":"20"}}},"color":{"type":"variable","id":"theme-4"},"typography":{"type":"variable","id":"YlLg3o","font":{"label":"Quicksand","value":"Quicksand","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"17","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":""}},"weight":"700"},"hoverTextColor":{"type":"variable","id":"theme-3"},"positioningType":{"Desktop":"inline"}} -->
<div class="guten-element guten-button-wrapper guten-pdbPzf"><a class="guten-button guten-button-sm" href="#"><span>Back To Home</span></a></div>
<!-- /wp:gutenverse/button --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
	'images'      => '',
	'is_sync' => false,
);
