<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Veterna About Gutenverse Adopt', 'veterna' ),
	'categories' => array( 'veterna-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1150"},"elementId":"guten-GKtfbE","background":{"type":"default","videoPlayOnMobile":false,"image":{"Desktop":[]},"color":{"r":242,"g":242,"b":238,"a":1}},"backgroundOverlay":{"type":"default","image":{"Desktop":{"id":221,"image":"https://designer.gutenverse.com/veterna/wp-content/uploads/sites/187/2025/03/bg2-freepik.webp"}},"position":{"Desktop":"bottom center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"}},"opacity":"0.05","margin":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"40","bottom":""}},"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"120","bottom":"100"}},"Mobile":{"unit":"px","dimension":{"top":"40","right":"0","bottom":"20","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"80","bottom":"40"}}},"zIndex":{"Tablet":1,"Desktop":1}} -->
<div class="section-wrapper" data-id="GKtfbE"><section class="wp-block-gutenverse-section guten-element guten-section guten-GKtfbE layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-container guten-column-gap-default"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null},"elementId":"guten-8fivvJ","horizontalAlign":{"Desktop":"center"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-8fivvJ"><div class="guten-column-wrapper" data-id="8fivvJ"><!-- wp:gutenverse/advanced-heading {"elementId":"guten-Dug08R","alignText":{"Desktop":"center"},"text":"","focusText":"How To Adopt ","subText":"How To Adopt Animals","showLine":"none","lineMargin":{"Desktop":[]},"mainMargin":{"Desktop":[]},"mainPadding":{"Desktop":[]},"focusColor":{"type":"variable","id":"theme-3"},"focusTypography":{"type":"variable","id":"ywYJC3","font":{"label":"Quicksand","value":"Quicksand","type":"google"},"size":{"Desktop":{"point":"20","unit":"px"},"Tablet":{"point":"19","unit":"px"},"Mobile":{"point":"18","unit":"px"}},"weight":"700"},"focusMargin":{"Desktop":[]},"focusPadding":{"Desktop":[]},"subColor":{"type":"variable","id":"theme-0"},"subTypography":{"type":"variable","id":"mG7K1R","font":{"label":"Quicksand","value":"Quicksand","type":"google"},"size":{"Desktop":{"point":"48","unit":"px"},"Tablet":{"point":"45","unit":"px"},"Mobile":{"point":"40","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"700"},"subMargin":{"Desktop":[]},"subPadding":{"Desktop":{"unit":"px","dimension":{"top":"20"}}},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"right":"10","left":"10"}}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":[]},"positioningType":{"Tablet":"custom"},"positioningWidth":{"Tablet":{"point":"649","unit":"px"}}} -->
<div class="guten-element guten-advanced-heading guten-Dug08R"><div class="heading-section "><h2 class="heading-title"><span class="heading-title"></span><span class="heading-focus">How To Adopt </span></h2></div><span class="heading-subtitle">How To Adopt Animals</span></div>
<!-- /wp:gutenverse/advanced-heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-KKvKEh","alignment":{"Desktop":"center"},"textColor":{"type":"variable","id":"theme-0"},"typography":{"type":"variable","id":"7MBQTH","font":{"label":"Quicksand","value":"Quicksand","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"15","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"unit":"em","point":"1.5"}}},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"35"}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"right":"10","left":"10"}}},"padding":{"Desktop":{"unit":"%","dimension":{"right":"25","left":"25"}},"Tablet":{"unit":"%","dimension":{"top":"","right":"20","bottom":"","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"positioningType":{"Mobile":"full"}} -->
<div class="guten-element gutenverse-text-editor guten-KKvKEh"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusm tempor incididunt ut labore et dolore magna aliqua.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/section {"layout":"fullwidth","isChild":true,"elementId":"guten-rYfn5K"} -->
<div class="section-wrapper" data-id="rYfn5K"><section class="wp-block-gutenverse-section guten-element guten-section guten-rYfn5K layout-fullwidth align-stretch"><div class="guten-container guten-column-gap-default"><!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":50,"Mobile":null},"elementId":"guten-ZqvdrP","margin":{"Tablet":{"unit":"px","dimension":{"top":"0","right":"40","bottom":"0","left":"40"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-ZqvdrP"><div class="guten-column-wrapper" data-id="ZqvdrP"><!-- wp:gutenverse/heading {"elementId":"guten-ADFjvQ","color":{"type":"variable","id":"theme-4"},"typography":{"type":"variable","id":"sYvmOz","font":{"label":"Quicksand","value":"Quicksand","type":"google"},"size":{"Desktop":{"point":"21","unit":"px"},"Tablet":{"point":"20","unit":"px"},"Mobile":{"point":"19","unit":"px"}},"weight":"700","transform":"default","lineHeight":{"Desktop":{"unit":"em","point":""}}},"containsAnchorTag":false,"background":{"type":"default","color":{"type":"variable","id":"theme-3"}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"-5"}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"11","bottom":"8","left":"11"}},"Mobile":[]},"positioningType":{"Desktop":"inline"},"positioningLocation":"default"} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-ADFjvQ">01.</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/icon-box {"elementId":"guten-Z1Cx5S","separateButtonLink":false,"title":"Select Your Animals","description":"Lorem ipsum dolor sit amet consecte.","iconType":"image","imageWidth":50,"imageHeight":50,"image":{"id":191,"image":"https://designer.gutenverse.com/veterna/wp-content/uploads/sites/187/2025/03/Asset-5-REZ364R.png"},"imageFit":"contain","iconPosition":"top","align":{"Desktop":"center"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"containerPaddingHover":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","left":"","right":"","bottom":""}}},"all":{"type":"none"}},"containerBorderResponsive":{"Mobile":{"radius":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}}},"containerBorderHover":{"radius":{"Desktop":[]}},"iconPadding":{"Desktop":[]},"iconMargin":{"Desktop":[]},"iconBorder":{"radius":{"Desktop":[]}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"20","left":"0"}}},"titleColor":{"type":"variable","id":"theme-0"},"titleTypography":{"type":"variable","id":"FCF0Au","font":{"label":"Quicksand","value":"Quicksand","type":"google"},"size":{"Desktop":{"point":"22","unit":"px"},"Tablet":{"point":"21","unit":"px"},"Mobile":{"point":"20","unit":"px"}},"weight":"700","lineHeight":{"Desktop":{"unit":"em","point":"0.2"}}},"descMargin":{"Desktop":[]},"descColor":{"type":"variable","id":"theme-0"},"descTypography":{"type":"variable","id":"7MBQTH","font":{"label":"Quicksand","value":"Quicksand","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"15","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"unit":"em","point":""}}},"badgePadding":{"Desktop":[]},"badgeMargin":{"Desktop":[]},"badgeRadius":{"Desktop":[]},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"40"}}},"padding":{"Desktop":[]},"parentSelector":".guten-Z1Cx5S:hover .guten-icon-box-wrapper"} -->
<div class="guten-element guten-Z1Cx5S guten-icon-box icon-position-top"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon bg-style-color type-image"><img src="https://designer.gutenverse.com/veterna/wp-content/uploads/sites/187/2025/03/Asset-5-REZ364R.png"/></div></div><div class="icon-box icon-box-body"><h2 class="title">Select Your Animals</h2><p class="icon-box-description">Lorem ipsum dolor sit amet consecte.</p></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":50,"Mobile":null},"elementId":"guten-5I4PFW","margin":{"Tablet":{"unit":"px","dimension":{"top":"0","right":"40","bottom":"0","left":"40"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-5I4PFW"><div class="guten-column-wrapper" data-id="5I4PFW"><!-- wp:gutenverse/heading {"elementId":"guten-GbjmrB","color":{"type":"variable","id":"theme-4"},"typography":{"type":"variable","id":"sYvmOz","font":{"label":"Quicksand","value":"Quicksand","type":"google"},"size":{"Desktop":{"point":"21","unit":"px"},"Tablet":{"point":"20","unit":"px"},"Mobile":{"point":"19","unit":"px"}},"weight":"700","transform":"default","lineHeight":{"Desktop":{"unit":"em","point":""}}},"containsAnchorTag":false,"background":{"type":"default","color":{"type":"variable","id":"theme-3"}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"-5"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"11","bottom":"8","left":"11"}}},"positioningType":{"Desktop":"inline"}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-GbjmrB">02.</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/icon-box {"elementId":"guten-yVEcU8","separateButtonLink":false,"title":"Make Appointment","description":"Lorem ipsum dolor sit amet consecte.","iconType":"image","imageWidth":50,"imageHeight":50,"image":{"id":657,"image":"https://designer.gutenverse.com/veterna/wp-content/uploads/sites/187/2025/03/Asset-10-REZ364R.png"},"imageFit":"contain","iconPosition":"top","align":{"Desktop":"center"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"containerPaddingHover":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","left":"","right":"","bottom":""}}},"all":{"type":"none"}},"containerBorderResponsive":{"Mobile":{"radius":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}}},"containerBorderHover":{"radius":{"Desktop":[]}},"iconPadding":{"Desktop":[]},"iconMargin":{"Desktop":[]},"iconBorder":{"radius":{"Desktop":[]}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"20","left":"0"}}},"titleColor":{"type":"variable","id":"theme-0"},"titleTypography":{"type":"variable","id":"FCF0Au","font":{"label":"Quicksand","value":"Quicksand","type":"google"},"size":{"Desktop":{"point":"22","unit":"px"},"Tablet":{"point":"21","unit":"px"},"Mobile":{"point":"20","unit":"px"}},"weight":"700","lineHeight":{"Desktop":{"unit":"em","point":"0.2"}}},"descMargin":{"Desktop":[]},"descColor":{"type":"variable","id":"theme-0"},"descTypography":{"type":"variable","id":"7MBQTH","font":{"label":"Quicksand","value":"Quicksand","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"15","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"unit":"em","point":""}}},"badgePadding":{"Desktop":[]},"badgeMargin":{"Desktop":[]},"badgeRadius":{"Desktop":[]},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"40"}}},"padding":{"Desktop":[]},"parentSelector":".guten-yVEcU8:hover .guten-icon-box-wrapper"} -->
<div class="guten-element guten-yVEcU8 guten-icon-box icon-position-top"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon bg-style-color type-image"><img src="https://designer.gutenverse.com/veterna/wp-content/uploads/sites/187/2025/03/Asset-10-REZ364R.png"/></div></div><div class="icon-box icon-box-body"><h2 class="title">Make Appointment</h2><p class="icon-box-description">Lorem ipsum dolor sit amet consecte.</p></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":50,"Mobile":null},"elementId":"guten-yxHCcq","margin":{"Tablet":{"unit":"px","dimension":{"right":"40","left":"40"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-yxHCcq"><div class="guten-column-wrapper" data-id="yxHCcq"><!-- wp:gutenverse/heading {"elementId":"guten-C4p6dU","color":{"type":"variable","id":"theme-4"},"typography":{"type":"variable","id":"sYvmOz","font":{"label":"Quicksand","value":"Quicksand","type":"google"},"size":{"Desktop":{"point":"21","unit":"px"},"Tablet":{"point":"20","unit":"px"},"Mobile":{"point":"19","unit":"px"}},"weight":"700","transform":"default","lineHeight":{"Desktop":{"unit":"em","point":""}}},"containsAnchorTag":false,"background":{"type":"default","color":{"type":"variable","id":"theme-3"}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"-5"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"11","bottom":"8","left":"11"}}},"positioningType":{"Desktop":"inline"}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-C4p6dU">03.</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/icon-box {"elementId":"guten-9sF1tU","separateButtonLink":false,"title":"Deal Your Pet","description":"Lorem ipsum dolor sit amet consecte.","iconType":"image","imageWidth":50,"imageHeight":50,"image":{"id":195,"image":"https://designer.gutenverse.com/veterna/wp-content/uploads/sites/187/2025/03/Asset-6-REZ364R.png"},"imageFit":"contain","iconPosition":"top","align":{"Desktop":"center"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"containerPaddingHover":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","left":"","right":"","bottom":""}}},"all":{"type":"none"}},"containerBorderResponsive":{"Mobile":{"radius":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}}},"containerBorderHover":{"radius":{"Desktop":[]}},"iconPadding":{"Desktop":[]},"iconMargin":{"Desktop":[]},"iconBorder":{"radius":{"Desktop":[]}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"20","left":"0"}}},"titleColor":{"type":"variable","id":"theme-0"},"titleTypography":{"type":"variable","id":"FCF0Au","font":{"label":"Quicksand","value":"Quicksand","type":"google"},"size":{"Desktop":{"point":"22","unit":"px"},"Tablet":{"point":"21","unit":"px"},"Mobile":{"point":"20","unit":"px"}},"weight":"700","lineHeight":{"Desktop":{"unit":"em","point":"0.2"}}},"descMargin":{"Desktop":[]},"descColor":{"type":"variable","id":"theme-0"},"descTypography":{"type":"variable","id":"7MBQTH","font":{"label":"Quicksand","value":"Quicksand","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"15","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"unit":"em","point":""}}},"badgePadding":{"Desktop":[]},"badgeMargin":{"Desktop":[]},"badgeRadius":{"Desktop":[]},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"40"}}},"padding":{"Desktop":[]},"parentSelector":".guten-9sF1tU:hover .guten-icon-box-wrapper"} -->
<div class="guten-element guten-9sF1tU guten-icon-box icon-position-top"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon bg-style-color type-image"><img src="https://designer.gutenverse.com/veterna/wp-content/uploads/sites/187/2025/03/Asset-6-REZ364R.png"/></div></div><div class="icon-box icon-box-body"><h2 class="title">Deal Your Pet</h2><p class="icon-box-description">Lorem ipsum dolor sit amet consecte.</p></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":50,"Mobile":null},"elementId":"guten-oYsoxU","margin":{"Tablet":{"unit":"px","dimension":{"right":"40","left":"40"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-oYsoxU"><div class="guten-column-wrapper" data-id="oYsoxU"><!-- wp:gutenverse/heading {"elementId":"guten-aPSWxw","color":{"type":"variable","id":"theme-4"},"typography":{"type":"variable","id":"sYvmOz","font":{"label":"Quicksand","value":"Quicksand","type":"google"},"size":{"Desktop":{"point":"21","unit":"px"},"Tablet":{"point":"20","unit":"px"},"Mobile":{"point":"19","unit":"px"}},"weight":"700","transform":"default","lineHeight":{"Desktop":{"unit":"em","point":""}}},"containsAnchorTag":false,"background":{"type":"default","color":{"type":"variable","id":"theme-3"}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"-5"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"11","bottom":"8","left":"11"}}},"positioningType":{"Desktop":"inline"}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-aPSWxw">04.</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/icon-box {"elementId":"guten-P600MH","separateButtonLink":false,"title":"Better With A Pet","description":"Lorem ipsum dolor sit amet consecte.","iconType":"image","imageWidth":50,"imageHeight":50,"image":{"id":658,"image":"https://designer.gutenverse.com/veterna/wp-content/uploads/sites/187/2025/03/Asset-11.png"},"imageFit":"contain","iconPosition":"top","align":{"Desktop":"center"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"containerPaddingHover":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","left":"","right":"","bottom":""}}},"all":{"type":"none"}},"containerBorderResponsive":{"Mobile":{"radius":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}}},"containerBorderHover":{"radius":{"Desktop":[]}},"iconPadding":{"Desktop":[]},"iconMargin":{"Desktop":[]},"iconBorder":{"radius":{"Desktop":[]}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"20","left":"0"}}},"titleColor":{"type":"variable","id":"theme-0"},"titleTypography":{"type":"variable","id":"FCF0Au","font":{"label":"Quicksand","value":"Quicksand","type":"google"},"size":{"Desktop":{"point":"22","unit":"px"},"Tablet":{"point":"21","unit":"px"},"Mobile":{"point":"20","unit":"px"}},"weight":"700","lineHeight":{"Desktop":{"unit":"em","point":"0.2"}}},"descMargin":{"Desktop":[]},"descColor":{"type":"variable","id":"theme-0"},"descTypography":{"type":"variable","id":"7MBQTH","font":{"label":"Quicksand","value":"Quicksand","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"15","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"unit":"em","point":""}}},"badgePadding":{"Desktop":[]},"badgeMargin":{"Desktop":[]},"badgeRadius":{"Desktop":[]},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"40"}}},"padding":{"Desktop":[]},"parentSelector":".guten-P600MH:hover .guten-icon-box-wrapper"} -->
<div class="guten-element guten-P600MH guten-icon-box icon-position-top"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon bg-style-color type-image"><img src="https://designer.gutenverse.com/veterna/wp-content/uploads/sites/187/2025/03/Asset-11.png"/></div></div><div class="icon-box icon-box-body"><h2 class="title">Better With A Pet</h2><p class="icon-box-description">Lorem ipsum dolor sit amet consecte.</p></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
	'images'      => '[{"name":"bg2-freepik.webp","image_url":"https:\/\/designer.gutenverse.com\/veterna\/wp-content\/uploads\/sites\/187\/2025\/03\/bg2-freepik.webp","type":"sync","id":1152,"image_id":221},{"name":"Asset-5-REZ364R.png","image_url":"https:\/\/designer.gutenverse.com\/veterna\/wp-content\/uploads\/sites\/187\/2025\/03\/Asset-5-REZ364R.png","type":"sync","id":1152,"image_id":191},{"name":"Asset-10-REZ364R.png","image_url":"https:\/\/designer.gutenverse.com\/veterna\/wp-content\/uploads\/sites\/187\/2025\/03\/Asset-10-REZ364R.png","type":"sync","id":1152,"image_id":657},{"name":"Asset-6-REZ364R.png","image_url":"https:\/\/designer.gutenverse.com\/veterna\/wp-content\/uploads\/sites\/187\/2025\/03\/Asset-6-REZ364R.png","type":"sync","id":1152,"image_id":195},{"name":"Asset-11.png","image_url":"https:\/\/designer.gutenverse.com\/veterna\/wp-content\/uploads\/sites\/187\/2025\/03\/Asset-11.png","type":"sync","id":1152,"image_id":658}]',
	'is_sync' => true,
);
