<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Veterna Home Gutenverse CTA', 'veterna' ),
	'categories' => array( 'veterna-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1150"},"elementId":"guten-MYFITN","background":{"type":"default","videoPlayOnMobile":false,"image":{"Desktop":[]},"color":{"r":242,"g":242,"b":238,"a":1}},"backgroundOverlay":{"type":"default","image":{"Desktop":{"id":221,"image":"https://designer.gutenverse.com/veterna/wp-content/uploads/sites/187/2025/03/bg2-freepik.webp"}},"position":{"Desktop":"bottom center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"}},"opacity":"0.05","margin":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"40"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"120","bottom":"120"}},"Mobile":{"unit":"px","dimension":{"top":"40","right":"10","bottom":"50","left":"10"}}},"zIndex":{"Tablet":1}} -->
<div class="section-wrapper" data-id="MYFITN"><section class="wp-block-gutenverse-section guten-element guten-section guten-MYFITN layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-container guten-column-gap-default"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-1Hif2Y","horizontalAlign":{"Desktop":"center"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-1Hif2Y"><div class="guten-column-wrapper" data-id="1Hif2Y"><!-- wp:gutenverse/advanced-heading {"elementId":"guten-yYSKlc","alignText":{"Desktop":"center"},"text":"","focusText":"Let\'s Care For Each Other","subText":"Contact Us If You Find Abandoned Animals","showLine":"none","lineMargin":{"Desktop":[]},"mainMargin":{"Desktop":[]},"mainPadding":{"Desktop":[]},"focusColor":{"type":"variable","id":"theme-3"},"focusTypography":{"type":"variable","id":"ywYJC3","font":{"label":"Quicksand","value":"Quicksand","type":"google"},"size":{"Desktop":{"point":"20","unit":"px"},"Tablet":{"point":"19","unit":"px"},"Mobile":{"point":"18","unit":"px"}},"weight":"700"},"focusMargin":{"Desktop":[]},"focusPadding":{"Desktop":[]},"subColor":{"type":"variable","id":"theme-0"},"subTypography":{"type":"variable","id":"mG7K1R","font":{"label":"Quicksand","value":"Quicksand","type":"google"},"size":{"Desktop":{"point":"48","unit":"px"},"Tablet":{"point":"45","unit":"px"},"Mobile":{"point":"40","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"700"},"subMargin":{"Desktop":[]},"subPadding":{"Desktop":{"unit":"px","dimension":{"top":"20"}}},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"positioningType":{"Tablet":"custom"},"positioningWidth":{"Tablet":{"point":"649","unit":"px"}}} -->
<div class="guten-element guten-advanced-heading guten-yYSKlc"><div class="heading-section "><h2 class="heading-title"><span class="heading-title"></span><span class="heading-focus">Let\'s Care For Each Other</span></h2></div><span class="heading-subtitle">Contact Us If You Find Abandoned Animals</span></div>
<!-- /wp:gutenverse/advanced-heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-RPSk51","alignment":{"Desktop":"center"},"textColor":{"type":"variable","id":"theme-0"},"typography":{"type":"variable","id":"7MBQTH","font":{"label":"Quicksand","value":"Quicksand","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"15","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"unit":"em","point":"1.5"}}},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"35"}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"%","dimension":{"right":"25","left":"25"}},"Tablet":{"unit":"%","dimension":{"top":"","right":"20","bottom":"","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"positioningType":{"Mobile":"full"}} -->
<div class="guten-element gutenverse-text-editor guten-RPSk51"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusm tempor incididunt ut labore et dolore magna aliqua.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/button {"elementId":"guten-MbLHg0","content":"(+62) 8152 254 239","alignButton":{"Desktop":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"18.5","bottom":"18.5","right":"35","left":"35"}},"Tablet":{"unit":"px","dimension":{"top":"17.25","bottom":"17.25","right":"35","left":"35"}},"Mobile":{"unit":"px","dimension":{"top":"18","bottom":"18"}}},"buttonBackground":{"type":"default","color":{"type":"variable","id":"theme-3"}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"theme-6"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}}},"showIcon":true,"icon":"fas fa-phone","iconSpacing":{"Desktop":"10"},"iconSize":{"Desktop":{"point":"15","unit":"px"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":""}}},"color":{"type":"variable","id":"theme-4"},"typography":{"type":"variable","id":"YlLg3o","font":{"label":"Quicksand","value":"Quicksand","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"17","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":""}},"weight":"700"},"hoverIconColor":{"type":"variable","id":"theme-3"},"hoverTextColor":{"type":"variable","id":"theme-3"},"positioningType":{"Desktop":"inline"}} -->
<div class="guten-element guten-button-wrapper guten-MbLHg0"><a class="guten-button guten-button-sm" href="#"><i class="fa-lg fas fa-phone"></i><span>(+62) 8152 254 239</span></a></div>
<!-- /wp:gutenverse/button --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
	'images'      => '[{"name":"bg2-freepik.webp","image_url":"https:\/\/designer.gutenverse.com\/veterna\/wp-content\/uploads\/sites\/187\/2025\/03\/bg2-freepik.webp","type":"sync","id":1138,"image_id":221}]',
	'is_sync' => true,
);
