<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Veterna Search Gutenverse Hero', 'veterna' ),
	'categories' => array( 'veterna-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1150"},"elementId":"guten-EYn6kt","background":{"videoPlayOnMobile":false,"type":"default","image":{"Desktop":{"id":889,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/cute-pet-e1636549536190.webp"}},"position":{"Desktop":"custom","Mobile":"custom"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"},"yposition":{"Desktop":{"unit":"%","point":"45"},"Mobile":{"point":"0","unit":"px"}},"xposition":{"Desktop":{"point":"0","unit":"px"},"Mobile":{"point":"0","unit":"px"}}},"backgroundOverlay":{"type":"default","color":{"r":0,"g":0,"b":0,"a":1}},"opacity":"0.3","margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"150","bottom":"85"}},"Tablet":{"unit":"px","dimension":{"right":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"150","right":"10","bottom":"80","left":"10"}}}} -->
<div class="section-wrapper" data-id="EYn6kt"><section class="wp-block-gutenverse-section guten-element guten-section guten-EYn6kt layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-container guten-column-gap-default"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null},"elementId":"guten-5XlHC4","horizontalAlign":{"Desktop":"default","Mobile":"center"},"margin":{"Mobile":{"unit":"px","dimension":{"bottom":""}}},"padding":{"Mobile":{"unit":"px","dimension":{"bottom":""}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-5XlHC4"><div class="guten-column-wrapper" data-id="5XlHC4"><!-- wp:gutenverse/search-result-title {"elementId":"guten-69HKHb","typography":{"type":"variable","id":"SVFas1","font":{"label":"Quicksand","value":"Quicksand","type":"google"},"size":{"Desktop":{"point":"55","unit":"px"},"Tablet":{"point":"50","unit":"px"},"Mobile":{"point":"45","unit":"px"}},"weight":"700","lineHeight":{"Desktop":{"unit":"em","point":"1.1"}}},"color":{"type":"variable","id":"theme-4"},"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"30"}}}} -->
<div class="guten-element guten-search-result-title guten-69HKHb"></div>
<!-- /wp:gutenverse/search-result-title -->

<!-- wp:gutenverse/search {"elementId":"guten-Vc6qKd","formStyle":{"Desktop":"fit-content","Mobile":"100%"},"buttonWidth":{"Desktop":{"unit":"px","point":"125"},"Mobile":{"unit":"%","point":"100"}},"positioningType":{"Mobile":"full","Desktop":"default"},"border":{"radius":{"Desktop":[]}},"borderResponsive":{"Mobile":{"radius":[]}},"margin":{"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"placeholderColor":{"Desktop":{"type":"variable","id":"theme-2"}},"inputPlaceholder":"Search...","inputPadding":{"Desktop":{"unit":"px","dimension":{"right":"25","left":"25"}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"inputMargin":{"Desktop":{"unit":"px","dimension":{"right":"16"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"16","left":"0"}}},"inputHeight":{"Desktop":"60"},"inputWidth":{"Desktop":{"unit":"%","point":"50"},"Mobile":{"unit":"%","point":"100"}},"inputTypography":{"type":"variable","id":"7MBQTH","font":{"label":"Quicksand","value":"Quicksand","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"15","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"unit":"em","point":"1.5"}}},"inputColorNormal":{"Desktop":{"type":"variable","id":"theme-0"}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}},"all":{"type":"solid","color":{"type":"variable","id":"theme-7"},"width":1}},"inputBorderNormalResponsive":{"Mobile":{"radius":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}},"inputBorderHover":{"radius":{"Desktop":[]}},"inputColorFocus":{"Desktop":{"type":"variable","id":"theme-0"}},"inputBorderFocus":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"theme-2"}}},"inputBgColorNormal":{"Desktop":{"r":249,"g":249,"b":249,"a":1}},"alignContent":{"Desktop":"flex-start"}} -->
<div class="guten-element guten-Vc6qKd guten-search"><form class="gutenverse-search-form"><div class="search-input-container"><input type="text" placeholder="Search..." name="s" class="gutenverse-search gutenverse-search-input"/><div class="close-icon"><i class="gtn gtn-x-line"></i></div></div><!-- wp:gutenverse/button {"elementId":"guten-SwRb3g","role":"submit","content":"Search","buttonSize":"xs","buttonWidth":{"Desktop":"","Mobile":"100"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"18","bottom":"18","right":"35","left":"35"}},"Mobile":[]},"buttonBackground":{"color":{"type":"variable","id":"theme-3"},"type":"default"},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"theme-6"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}}},"buttonBorderHover":{"radius":{"Desktop":[]}},"color":{"type":"variable","id":"theme-4"},"typography":{"type":"variable","id":"YtKk3z","font":{"label":"Quicksand","value":"Quicksand","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"15","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"700","lineHeight":{"Desktop":{"unit":"em","point":"1.5"}}},"hoverTextColor":{"type":"variable","id":"theme-3"},"positioningType":{"Mobile":"full","Desktop":"default"}} -->
<div class="guten-element guten-button-wrapper guten-SwRb3g"><button class="guten-button guten-button-xs" type="submit"><span>Search</span></button></div>
<!-- /wp:gutenverse/button --></form></div>
<!-- /wp:gutenverse/search --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
	'images'      => '',
	'is_sync' => false,
);
