<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Veterna About Gutenverse About', 'veterna' ),
	'categories' => array( 'veterna-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"elementId":"guten-bt1CqO","margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"120"}},"Tablet":{"unit":"px","dimension":{"right":"10","left":"10","top":"80","bottom":"80"}},"Mobile":{"unit":"px","dimension":{"top":"40","bottom":"40"}}},"zIndex":{"Tablet":1,"Desktop":1}} -->
<div class="section-wrapper" data-id="bt1CqO"><section class="wp-block-gutenverse-section guten-element guten-section guten-bt1CqO layout-boxed align-stretch"><div class="guten-container guten-column-gap-default"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100},"elementId":"guten-zIL5K9","margin":{"Desktop":{"unit":"px","dimension":{"left":"-10"}},"Tablet":{"unit":"px","dimension":{"bottom":"50","left":"0","right":"0"}}},"padding":{"Desktop":[],"Tablet":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-zIL5K9"><div class="guten-column-wrapper" data-id="zIL5K9"><!-- wp:gutenverse/advanced-heading {"elementId":"guten-EmBqnQ","alignText":{"Desktop":"flex-start"},"text":"","focusText":"About Veterna","subText":"We\'re The World\'s Most Trusted Animal Rescue","showLine":"none","lineMargin":{"Desktop":[]},"mainMargin":{"Desktop":[]},"mainPadding":{"Desktop":[]},"focusColor":{"type":"variable","id":"theme-3"},"focusTypography":{"type":"variable","id":"ywYJC3","font":{"label":"Quicksand","value":"Quicksand","type":"google"},"size":{"Desktop":{"point":"20","unit":"px"},"Tablet":{"point":"19","unit":"px"},"Mobile":{"point":"18","unit":"px"}},"weight":"700"},"focusMargin":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"focusPadding":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"subColor":{"type":"variable","id":"theme-0"},"subTypography":{"type":"variable","id":"mG7K1R","font":{"label":"Quicksand","value":"Quicksand","type":"google"},"size":{"Desktop":{"point":"48","unit":"px"},"Tablet":{"point":"45","unit":"px"},"Mobile":{"point":"40","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"700"},"subMargin":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}}},"subPadding":{"Desktop":{"unit":"px","dimension":{"top":"20"}},"Tablet":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}}},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"positioningType":{"Tablet":"custom"},"positioningWidth":{"Tablet":{"point":"","unit":"px"}}} -->
<div class="guten-element guten-advanced-heading guten-EmBqnQ"><div class="heading-section "><h2 class="heading-title"><span class="heading-title"></span><span class="heading-focus">About Veterna</span></h2></div><span class="heading-subtitle">We\'re The World\'s Most Trusted Animal Rescue</span></div>
<!-- /wp:gutenverse/advanced-heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-7Eu816","alignment":{"Desktop":"left"},"textColor":{"type":"variable","id":"theme-2"},"typography":{"type":"variable","id":"7MBQTH","font":{"label":"Quicksand","value":"Quicksand","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"15","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"unit":"em","point":"1.5"}}},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"25"}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":null},"positioningType":{"Desktop":"default","Tablet":"full"},"positioningWidth":{"Desktop":{"point":"","unit":"px"}}} -->
<div class="guten-element gutenverse-text-editor guten-7Eu816"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/section {"layout":"fullwidth","isChild":true,"gap":"no","elementId":"guten-iB0kHH","zIndex":{"Tablet":null}} -->
<div class="section-wrapper" data-id="iB0kHH"><section class="wp-block-gutenverse-section guten-element guten-section guten-iB0kHH layout-fullwidth align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50},"elementId":"guten-iVne4W","margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":"20"}}},"zIndex":{"Tablet":null}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-iVne4W"><div class="guten-column-wrapper" data-id="iVne4W"><!-- wp:gutenverse/icon-box {"elementId":"guten-pN0trP","separateButtonLink":false,"title":"Pet Donations","description":"Lorem ipsum dolor sit amet consectetur.","iconType":"image","imageWidth":45,"imageHeight":45,"image":{"id":151,"image":"https://designer.gutenverse.com/veterna/wp-content/uploads/sites/187/2025/02/Asset-4-REZ364R.png"},"imageFit":"contain","iconPosition":"left","align":{"Desktop":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"containerPaddingHover":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","left":"","right":"","bottom":""}}},"all":{"type":"none"}},"containerBorderResponsive":{"Mobile":{"radius":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}}},"containerBorderHover":{"radius":{"Desktop":[]}},"iconPadding":{"Desktop":[]},"iconMargin":{"Desktop":[]},"iconBorder":{"radius":{"Desktop":[]}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"titleColor":{"type":"variable","id":"theme-0"},"titleTypography":{"type":"variable","id":"XYTR8w","font":{"label":"Quicksand","value":"Quicksand","type":"google"},"size":{"Desktop":{"point":"24","unit":"px"},"Tablet":{"point":"23","unit":"px"},"Mobile":{"point":"22","unit":"px"}},"weight":"700","lineHeight":{"Desktop":{"unit":"em","point":""}}},"descMargin":{"Desktop":[]},"descColor":{"type":"variable","id":"theme-2"},"descTypography":{"type":"variable","id":"7MBQTH","font":{"label":"Quicksand","value":"Quicksand","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"15","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"unit":"em","point":""}}},"badgePadding":{"Desktop":[]},"badgeMargin":{"Desktop":[]},"badgeRadius":{"Desktop":[]},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"40"}}},"padding":{"Desktop":[]},"zIndex":{"Tablet":null},"parentSelector":".guten-pN0trP:hover .guten-icon-box-wrapper"} -->
<div class="guten-element guten-pN0trP guten-icon-box icon-position-left"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon bg-style-color type-image"><img src="https://designer.gutenverse.com/veterna/wp-content/uploads/sites/187/2025/02/Asset-4-REZ364R.png"/></div></div><div class="icon-box icon-box-body"><h2 class="title">Pet Donations</h2><p class="icon-box-description">Lorem ipsum dolor sit amet consectetur.</p></div></div></div>
<!-- /wp:gutenverse/icon-box -->

<!-- wp:gutenverse/icon-box {"elementId":"guten-nNkgI5","separateButtonLink":false,"title":"Adopt Animal","description":"Lorem ipsum dolor sit amet consectetur.","iconType":"image","imageWidth":45,"imageHeight":45,"image":{"id":166,"image":"https://designer.gutenverse.com/veterna/wp-content/uploads/sites/187/2025/03/Asset-3-REZ364R.png"},"imageFit":"contain","iconPosition":"left","align":{"Desktop":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"containerPaddingHover":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","left":"","right":"","bottom":""}}},"all":{"type":"none"}},"containerBorderResponsive":{"Mobile":{"radius":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}}},"containerBorderHover":{"radius":{"Desktop":[]}},"iconPadding":{"Desktop":[]},"iconMargin":{"Desktop":[]},"iconBorder":{"radius":{"Desktop":[]}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"titleColor":{"type":"variable","id":"theme-0"},"titleTypography":{"type":"variable","id":"XYTR8w","font":{"label":"Quicksand","value":"Quicksand","type":"google"},"size":{"Desktop":{"point":"24","unit":"px"},"Tablet":{"point":"23","unit":"px"},"Mobile":{"point":"22","unit":"px"}},"weight":"700","lineHeight":{"Desktop":{"unit":"em","point":""}}},"descMargin":{"Desktop":[]},"descColor":{"type":"variable","id":"theme-2"},"descTypography":{"type":"variable","id":"7MBQTH","font":{"label":"Quicksand","value":"Quicksand","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"15","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"unit":"em","point":""}}},"badgePadding":{"Desktop":[]},"badgeMargin":{"Desktop":[]},"badgeRadius":{"Desktop":[]},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":""}}},"padding":{"Desktop":[]},"zIndex":{"Tablet":null},"parentSelector":".guten-nNkgI5:hover .guten-icon-box-wrapper"} -->
<div class="guten-element guten-nNkgI5 guten-icon-box icon-position-left"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon bg-style-color type-image"><img src="https://designer.gutenverse.com/veterna/wp-content/uploads/sites/187/2025/03/Asset-3-REZ364R.png"/></div></div><div class="icon-box icon-box-body"><h2 class="title">Adopt Animal</h2><p class="icon-box-description">Lorem ipsum dolor sit amet consectetur.</p></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":null},"elementId":"guten-4a7kUn","margin":{"Desktop":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"40","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-4a7kUn"><div class="guten-column-wrapper" data-id="4a7kUn"><!-- wp:gutenverse/icon-box {"elementId":"guten-6UJgt6","separateButtonLink":false,"title":"Animal Rescue","description":"Lorem ipsum dolor sit amet consectetur.","iconType":"image","imageWidth":50,"imageHeight":50,"image":{"id":161,"image":"https://designer.gutenverse.com/veterna/wp-content/uploads/sites/187/2025/03/Asset-2-REZ364R.png"},"imageFit":"contain","iconPosition":"left","align":{"Desktop":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"containerPaddingHover":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","left":"","right":"","bottom":""}}},"all":{"type":"none"}},"containerBorderResponsive":{"Mobile":{"radius":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}}},"containerBorderHover":{"radius":{"Desktop":[]}},"iconPadding":{"Desktop":[]},"iconMargin":{"Desktop":[]},"iconBorder":{"radius":{"Desktop":[]}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"titleColor":{"type":"variable","id":"theme-0"},"titleTypography":{"type":"variable","id":"XYTR8w","font":{"label":"Quicksand","value":"Quicksand","type":"google"},"size":{"Desktop":{"point":"24","unit":"px"},"Tablet":{"point":"23","unit":"px"},"Mobile":{"point":"22","unit":"px"}},"weight":"700","lineHeight":{"Desktop":{"unit":"em","point":""}}},"descMargin":{"Desktop":[]},"descColor":{"type":"variable","id":"theme-2"},"descTypography":{"type":"variable","id":"7MBQTH","font":{"label":"Quicksand","value":"Quicksand","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"15","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"unit":"em","point":""}}},"badgePadding":{"Desktop":[]},"badgeMargin":{"Desktop":[]},"badgeRadius":{"Desktop":[]},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"40"}}},"padding":{"Desktop":[]},"parentSelector":".guten-6UJgt6:hover .guten-icon-box-wrapper"} -->
<div class="guten-element guten-6UJgt6 guten-icon-box icon-position-left"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon bg-style-color type-image"><img src="https://designer.gutenverse.com/veterna/wp-content/uploads/sites/187/2025/03/Asset-2-REZ364R.png"/></div></div><div class="icon-box icon-box-body"><h2 class="title">Animal Rescue</h2><p class="icon-box-description">Lorem ipsum dolor sit amet consectetur.</p></div></div></div>
<!-- /wp:gutenverse/icon-box -->

<!-- wp:gutenverse/icon-box {"elementId":"guten-YP0JB9","separateButtonLink":false,"title":"Animal Care","description":"Lorem ipsum dolor sit amet consectetur.","iconType":"image","imageWidth":45,"imageHeight":45,"image":{"id":201,"image":"https://designer.gutenverse.com/veterna/wp-content/uploads/sites/187/2025/03/Asset-7-REZ364R.png"},"imageFit":"contain","iconPosition":"left","align":{"Desktop":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"containerPaddingHover":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","left":"","right":"","bottom":""}}},"all":{"type":"none"}},"containerBorderResponsive":{"Mobile":{"radius":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}}},"containerBorderHover":{"radius":{"Desktop":[]}},"iconPadding":{"Desktop":[]},"iconMargin":{"Desktop":[]},"iconBorder":{"radius":{"Desktop":[]}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"titleColor":{"type":"variable","id":"theme-0"},"titleTypography":{"type":"variable","id":"XYTR8w","font":{"label":"Quicksand","value":"Quicksand","type":"google"},"size":{"Desktop":{"point":"24","unit":"px"},"Tablet":{"point":"23","unit":"px"},"Mobile":{"point":"22","unit":"px"}},"weight":"700","lineHeight":{"Desktop":{"unit":"em","point":""}}},"descMargin":{"Desktop":[]},"descColor":{"type":"variable","id":"theme-2"},"descTypography":{"type":"variable","id":"7MBQTH","font":{"label":"Quicksand","value":"Quicksand","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"15","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"unit":"em","point":""}}},"badgePadding":{"Desktop":[]},"badgeMargin":{"Desktop":[]},"badgeRadius":{"Desktop":[]},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":""}}},"padding":{"Desktop":[]},"parentSelector":".guten-YP0JB9:hover .guten-icon-box-wrapper"} -->
<div class="guten-element guten-YP0JB9 guten-icon-box icon-position-left"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon bg-style-color type-image"><img src="https://designer.gutenverse.com/veterna/wp-content/uploads/sites/187/2025/03/Asset-7-REZ364R.png"/></div></div><div class="icon-box icon-box-body"><h2 class="title">Animal Care</h2><p class="icon-box-description">Lorem ipsum dolor sit amet consectetur.</p></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":50},"elementId":"guten-OZtKZE","margin":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"left":"30"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-OZtKZE"><div class="guten-column-wrapper" data-id="OZtKZE"><!-- wp:gutenverse/section {"layout":"fullwidth","isChild":true,"gap":"no","elementId":"guten-Ne63Yh","margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}}} -->
<div class="section-wrapper" data-id="Ne63Yh"><section class="wp-block-gutenverse-section guten-element guten-section guten-Ne63Yh layout-fullwidth align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-N0UMil","background":{"type":"default","color":{"type":"variable","id":"theme-3"}},"backgroundOverlay":{"type":"default","image":{"Desktop":{"id":221,"image":"https://designer.gutenverse.com/veterna/wp-content/uploads/sites/187/2025/03/bg2-freepik.webp"}},"size":{"Desktop":"cover"}},"opacity":"0.1","border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}}},"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-N0UMil"><div class="guten-column-wrapper" data-id="N0UMil"><div class="guten-background-overlay"></div><!-- wp:gutenverse/advanced-heading {"elementId":"guten-0wwC0Y","text":"","focusText":"Love \u0026 Pets","subText":"Animal Rescue","showLine":"none","lineMargin":{"Desktop":[]},"focusColor":{"type":"variable","id":"theme-4"},"focusTypography":{"type":"variable","id":"FCF0Au","font":{"label":"Quicksand","value":"Quicksand","type":"google"},"size":{"Desktop":{"point":"22","unit":"px"},"Tablet":{"point":"21","unit":"px"},"Mobile":{"point":"20","unit":"px"}},"weight":"700","lineHeight":{"Desktop":{"unit":"em","point":"0.2"}}},"focusMargin":{"Desktop":[]},"focusPadding":{"Desktop":[]},"subColor":{"type":"variable","id":"theme-4"},"subTypography":{"type":"variable","id":"7MBQTH","font":{"label":"Quicksand","value":"Quicksand","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"15","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"unit":"em","point":"1.5"}}},"subMargin":{"Desktop":[]},"subPadding":{"Desktop":[]},"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}}} -->
<div class="guten-element guten-advanced-heading guten-0wwC0Y"><div class="heading-section "><h2 class="heading-title"><span class="heading-title"></span><span class="heading-focus">Love & Pets</span></h2></div><span class="heading-subtitle">Animal Rescue</span></div>
<!-- /wp:gutenverse/advanced-heading -->

<!-- wp:gutenverse/fun-fact {"elementId":"guten-wx1qhh","iconType":"none","iconBorder":{"radius":{"Desktop":[]}},"iconPadding":{"Desktop":[]},"iconMargin":{"Desktop":[]},"prefix":"","number":"16,789","suffix":"","title":"","showSupper":true,"superColor":{"type":"variable","id":"theme-4"},"superTypography":{"type":"variable","id":"FeNByJ","font":{"label":"Quicksand","value":"Quicksand","type":"google"},"size":{"Desktop":{"point":"30","unit":"px"},"Tablet":{"point":"28","unit":"px"},"Mobile":{"point":"26","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":""}},"weight":"600"},"superAlign":{"Desktop":"baseline"},"alignButtons":{"Desktop":"left"},"numberColor":{"Desktop":{"type":"variable","id":"theme-4"}},"numberTypography":{"type":"variable","id":"zP9amr","font":{"label":"Quicksand","value":"Quicksand","type":"google"},"size":{"Desktop":{"point":"40","unit":"px"},"Tablet":{"point":"38","unit":"px"},"Mobile":{"point":"35","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":""}},"weight":"700"},"contentPadding":{"Desktop":[]}} -->
<div class="guten-element guten-wx1qhh guten-fun-fact align-center hover-from-left"><div class="fun-fact-inner"><div class="content"><div class="number-wrapper"><span class="prefix"></span><span class="number loaded" data-number="16,789" data-duration="3500"></span><span class="suffix"></span><sup class="super">+</sup></div><span class="title"></span></div></div></div>
<!-- /wp:gutenverse/fun-fact --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"layout":"fullwidth","isChild":true,"gap":"no","elementId":"guten-gnNR9r","background":{"videoPlayOnMobile":false,"type":"default","image":{"Desktop":{"id":623,"image":"https://designer.gutenverse.com/veterna/wp-content/uploads/sites/187/2025/03/cute-fluffy-cat-playing-in-shelter-helping-animals-charity-philanthropy-e1636548493692.webp"}},"position":{"Desktop":"default"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}}},"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}}} -->
<div class="section-wrapper" data-id="gnNR9r"><section class="wp-block-gutenverse-section guten-element guten-section guten-gnNR9r layout-fullwidth align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-pvsxYd"} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-pvsxYd"><div class="guten-column-wrapper" data-id="pvsxYd"><!-- wp:gutenverse/spacer {"elementId":"guten-o7x13D","space":{"Desktop":{"point":"300","unit":"px"}}} -->
<div class="guten-element guten-spacer guten-o7x13D"></div>
<!-- /wp:gutenverse/spacer --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":25,"Tablet":50},"elementId":"guten-H4oGCm"} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-H4oGCm"><div class="guten-column-wrapper" data-id="H4oGCm"><!-- wp:gutenverse/section {"layout":"fullwidth","isChild":true,"gap":"no","elementId":"guten-C6Qiog","background":{"videoPlayOnMobile":false,"type":"default","image":{"Desktop":{"id":632,"image":"https://designer.gutenverse.com/veterna/wp-content/uploads/sites/187/2025/03/small-puppies-of-stray-dogs-e1636548476232.webp"}},"position":{"Desktop":"bottom center","Tablet":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"},"yposition":{"Tablet":{"unit":"%","point":"66"}}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}}},"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}}} -->
<div class="section-wrapper" data-id="C6Qiog"><section class="wp-block-gutenverse-section guten-element guten-section guten-C6Qiog layout-fullwidth align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-o3L2is"} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-o3L2is"><div class="guten-column-wrapper" data-id="o3L2is"><!-- wp:gutenverse/spacer {"elementId":"guten-spCqy2","space":{"Desktop":{"point":"300","unit":"px"}}} -->
<div class="guten-element guten-spacer guten-spCqy2"></div>
<!-- /wp:gutenverse/spacer --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"layout":"fullwidth","isChild":true,"gap":"no","elementId":"guten-k2ifee","margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"20"}}}} -->
<div class="section-wrapper" data-id="k2ifee"><section class="wp-block-gutenverse-section guten-element guten-section guten-k2ifee layout-fullwidth align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-9PdsPv","background":{"type":"default","color":{"r":242,"g":242,"b":238,"a":1}},"backgroundOverlay":{"type":"default","image":{"Desktop":{"id":633,"image":"https://designer.gutenverse.com/veterna/wp-content/uploads/sites/187/2025/03/bg3-freepik.png"}},"size":{"Desktop":"cover"}},"opacity":"0.03","border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}}},"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-9PdsPv"><div class="guten-column-wrapper" data-id="9PdsPv"><div class="guten-background-overlay"></div><!-- wp:gutenverse/advanced-heading {"elementId":"guten-GoaiFb","text":"","focusText":"Animal Fund","subText":"Donations","showLine":"none","lineMargin":{"Desktop":[]},"focusColor":{"type":"variable","id":"theme-0"},"focusTypography":{"type":"variable","id":"FCF0Au","font":{"label":"Quicksand","value":"Quicksand","type":"google"},"size":{"Desktop":{"point":"22","unit":"px"},"Tablet":{"point":"21","unit":"px"},"Mobile":{"point":"20","unit":"px"}},"weight":"700","lineHeight":{"Desktop":{"unit":"em","point":"0.2"}}},"focusMargin":{"Desktop":[]},"focusPadding":{"Desktop":[]},"subColor":{"type":"variable","id":"theme-3"},"subTypography":{"type":"variable","id":"7MBQTH","font":{"label":"Quicksand","value":"Quicksand","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"15","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"unit":"em","point":"1.5"}}},"subMargin":{"Desktop":[]},"subPadding":{"Desktop":[]},"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}}} -->
<div class="guten-element guten-advanced-heading guten-GoaiFb"><div class="heading-section "><h2 class="heading-title"><span class="heading-title"></span><span class="heading-focus">Animal Fund</span></h2></div><span class="heading-subtitle">Donations</span></div>
<!-- /wp:gutenverse/advanced-heading -->

<!-- wp:gutenverse/fun-fact {"elementId":"guten-DR7o0f","iconType":"none","iconBorder":{"radius":{"Desktop":[]}},"iconPadding":{"Desktop":[]},"iconMargin":{"Desktop":[]},"prefix":"","number":"11,563","suffix":"","title":"","showSupper":true,"superColor":{"type":"variable","id":"theme-0"},"superTypography":{"type":"variable","id":"FeNByJ","font":{"label":"Quicksand","value":"Quicksand","type":"google"},"size":{"Desktop":{"point":"30","unit":"px"},"Tablet":{"point":"28","unit":"px"},"Mobile":{"point":"26","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":""}},"weight":"600"},"superAlign":{"Desktop":"baseline"},"alignButtons":{"Desktop":"left"},"numberColor":{"Desktop":{"type":"variable","id":"theme-0"}},"numberTypography":{"type":"variable","id":"zP9amr","font":{"label":"Quicksand","value":"Quicksand","type":"google"},"size":{"Desktop":{"point":"40","unit":"px"},"Tablet":{"point":"38","unit":"px"},"Mobile":{"point":"35","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":""}},"weight":"700"},"contentPadding":{"Desktop":[]}} -->
<div class="guten-element guten-DR7o0f guten-fun-fact align-center hover-from-left"><div class="fun-fact-inner"><div class="content"><div class="number-wrapper"><span class="prefix"></span><span class="number loaded" data-number="11,563" data-duration="3500"></span><span class="suffix"></span><sup class="super">+</sup></div><span class="title"></span></div></div></div>
<!-- /wp:gutenverse/fun-fact --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
	'images'      => '[{"name":"Asset-4-REZ364R.png","image_url":"https:\/\/designer.gutenverse.com\/veterna\/wp-content\/uploads\/sites\/187\/2025\/02\/Asset-4-REZ364R.png","type":"sync","id":1151,"image_id":151},{"name":"Asset-3-REZ364R.png","image_url":"https:\/\/designer.gutenverse.com\/veterna\/wp-content\/uploads\/sites\/187\/2025\/03\/Asset-3-REZ364R.png","type":"sync","id":1151,"image_id":166},{"name":"Asset-2-REZ364R.png","image_url":"https:\/\/designer.gutenverse.com\/veterna\/wp-content\/uploads\/sites\/187\/2025\/03\/Asset-2-REZ364R.png","type":"sync","id":1151,"image_id":161},{"name":"Asset-7-REZ364R.png","image_url":"https:\/\/designer.gutenverse.com\/veterna\/wp-content\/uploads\/sites\/187\/2025\/03\/Asset-7-REZ364R.png","type":"sync","id":1151,"image_id":201},{"name":"bg2-freepik.webp","image_url":"https:\/\/designer.gutenverse.com\/veterna\/wp-content\/uploads\/sites\/187\/2025\/03\/bg2-freepik.webp","type":"sync","id":1151,"image_id":221},{"name":"cute-fluffy-cat-playing-in-shelter-helping-animals-charity-philanthropy-e1636548493692.webp","image_url":"https:\/\/designer.gutenverse.com\/veterna\/wp-content\/uploads\/sites\/187\/2025\/03\/cute-fluffy-cat-playing-in-shelter-helping-animals-charity-philanthropy-e1636548493692.webp","type":"sync","id":1151,"image_id":623},{"name":"small-puppies-of-stray-dogs-e1636548476232.webp","image_url":"https:\/\/designer.gutenverse.com\/veterna\/wp-content\/uploads\/sites\/187\/2025\/03\/small-puppies-of-stray-dogs-e1636548476232.webp","type":"sync","id":1151,"image_id":632},{"name":"bg3-freepik.png","image_url":"https:\/\/designer.gutenverse.com\/veterna\/wp-content\/uploads\/sites\/187\/2025\/03\/bg3-freepik.png","type":"sync","id":1151,"image_id":633}]',
	'is_sync' => true,
);
