<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Veterna Home Gutenverse Funfact', 'veterna' ),
	'categories' => array( 'veterna-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1150"},"elementId":"guten-Tb6irO","background":{"videoPlayOnMobile":false,"type":"default","color":{"type":"variable","id":"theme-7"}},"backgroundOverlay":{"type":"default","image":{"Desktop":{"id":221,"image":"https://designer.gutenverse.com/veterna/wp-content/uploads/sites/187/2025/03/bg2-freepik.webp"}},"repeat":{"Tablet":"no-repeat"},"size":{"Tablet":"cover"}},"opacity":"0.05","margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":""}},"Tablet":{"unit":"px","dimension":{"right":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"bottom":"80","top":"40"}}},"zIndex":{"Tablet":1}} -->
<div class="section-wrapper" data-id="Tb6irO"><section class="wp-block-gutenverse-section guten-element guten-section guten-Tb6irO layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-container guten-column-gap-default"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100},"elementId":"guten-w8mlfm","order":{"Desktop":"1","Tablet":2},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"-120","top":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":""}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-w8mlfm"><div class="guten-column-wrapper" data-id="w8mlfm"><!-- wp:gutenverse/image {"elementId":"guten-QTIueX","imgSrc":{"media":{"imageId":252,"sizes":{"thumbnail":{"height":150,"width":150,"url":"https://designer.gutenverse.com/veterna/wp-content/uploads/sites/187/2025/03/woman-volunteer-meeting-homeless-dog-puppies-in-fall-nature-background-pet-love-caring-for-pets-e1636548359393.webp","orientation":"landscape"},"medium":{"height":300,"width":200,"url":"https://designer.gutenverse.com/veterna/wp-content/uploads/sites/187/2025/03/woman-volunteer-meeting-homeless-dog-puppies-in-fall-nature-background-pet-love-caring-for-pets-e1636548359393.webp","orientation":"portrait"},"large":{"height":1024,"width":683,"url":"https://designer.gutenverse.com/veterna/wp-content/uploads/sites/187/2025/03/woman-volunteer-meeting-homeless-dog-puppies-in-fall-nature-background-pet-love-caring-for-pets-e1636548359393.webp","orientation":"portrait"},"full":{"url":"https://designer.gutenverse.com/veterna/wp-content/uploads/sites/187/2025/03/woman-volunteer-meeting-homeless-dog-puppies-in-fall-nature-background-pet-love-caring-for-pets-e1636548359393.webp","height":1500,"width":1000,"orientation":"portrait"}}},"size":"full"},"altOriginal":"","captionOriginal":"","imgBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}}},"imgBorderResponsive":{"Tablet":{"radius":[]}},"hideMobile":true,"margin":{"Desktop":[]},"padding":{"Desktop":[]},"positioningType":{"Desktop":"custom","Tablet":"custom"},"positioningWidth":{"Desktop":{"unit":"%","point":"91"},"Tablet":{"unit":"%","point":"60"}}} -->
<div class="wp-block-gutenverse-image guten-element guten-image guten-QTIueX hide-mobile"><div class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="https://designer.gutenverse.com/veterna/wp-content/uploads/sites/187/2025/03/woman-volunteer-meeting-homeless-dog-puppies-in-fall-nature-background-pet-love-caring-for-pets-e1636548359393.webp" height="1500" width="1000"/></div></div>
<!-- /wp:gutenverse/image --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100},"elementId":"guten-o9Epyi","margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"10","bottom":""}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-o9Epyi"><div class="guten-column-wrapper" data-id="o9Epyi"><!-- wp:gutenverse/advanced-heading {"elementId":"guten-ZSWzXH","alignText":{"Desktop":"flex-start"},"text":"","focusText":"Fun Fact Must You Know","subText":"You Have The Power To Change Tomorrow","showLine":"none","lineMargin":{"Desktop":[]},"mainMargin":{"Desktop":[]},"mainPadding":{"Desktop":[]},"focusColor":{"type":"variable","id":"theme-3"},"focusTypography":{"type":"variable","id":"ywYJC3","font":{"label":"Quicksand","value":"Quicksand","type":"google"},"size":{"Desktop":{"point":"20","unit":"px"},"Tablet":{"point":"19","unit":"px"},"Mobile":{"point":"18","unit":"px"}},"weight":"700"},"focusMargin":{"Desktop":[]},"focusPadding":{"Desktop":[]},"subColor":{"type":"variable","id":"theme-0"},"subTypography":{"type":"variable","id":"mG7K1R","font":{"label":"Quicksand","value":"Quicksand","type":"google"},"size":{"Desktop":{"point":"48","unit":"px"},"Tablet":{"point":"45","unit":"px"},"Mobile":{"point":"40","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"700"},"subMargin":{"Desktop":[]},"subPadding":{"Desktop":{"unit":"px","dimension":{"top":"20"}}},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"positioningType":{"Tablet":"custom"},"positioningWidth":{"Tablet":{"point":"","unit":"px"}}} -->
<div class="guten-element guten-advanced-heading guten-ZSWzXH"><div class="heading-section "><h2 class="heading-title"><span class="heading-title"></span><span class="heading-focus">Fun Fact Must You Know</span></h2></div><span class="heading-subtitle">You Have The Power To Change Tomorrow</span></div>
<!-- /wp:gutenverse/advanced-heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-noPtlK","alignment":{"Desktop":"left"},"textColor":{"type":"variable","id":"theme-0"},"typography":{"type":"variable","id":"7MBQTH","font":{"label":"Quicksand","value":"Quicksand","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"15","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"unit":"em","point":"1.5"}}},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"25"}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":400},"positioningType":{"Desktop":"default","Tablet":"full"},"positioningWidth":{"Desktop":{"point":"","unit":"px"}}} -->
<div class="guten-element gutenverse-text-editor guten-noPtlK animated guten-element-hide desktop-fadeInRight"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusm tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam quis nostrud exercitation ullamco laboris.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-vUyzz8","margin":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"0","bottom":"50","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"10","right":"0","bottom":"20","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"-3","left":""}},"Mobile":[]}} -->
<div class="section-wrapper" data-id="vUyzz8"><section class="wp-block-gutenverse-section guten-element guten-section guten-vUyzz8 layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":null,"Mobile":100},"elementId":"guten-jr9iep","margin":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[]},"padding":{"Tablet":{"unit":"px","dimension":{"top":"0","right":"40","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"right":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-jr9iep"><div class="guten-column-wrapper" data-id="jr9iep"><!-- wp:gutenverse/wrapper {"elementId":"guten-yTRfaH","displayType":"flex","displayWidth":{"Desktop":{"point":"130","unit":"px"},"Tablet":{"point":"130","unit":"px"},"Mobile":{"point":"150","unit":"px"}},"displayHeight":{"Desktop":{"point":"130","unit":"px"},"Tablet":{"point":"130","unit":"px"},"Mobile":{"point":"150","unit":"px"}},"verticalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"background":{"type":"default","image":{"Desktop":{"id":256,"image":"https://designer.gutenverse.com/veterna/wp-content/uploads/sites/187/2025/03/95-percent.png"}},"size":{"Desktop":"custom"},"width":{"Desktop":{"point":"130","unit":"px"}},"position":{"Desktop":"default","Tablet":"center center"},"repeat":{"Tablet":"no-repeat"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"15","left":"0"}},"Tablet":{"unit":"px","dimension":{"left":""}}},"padding":{"Desktop":[],"Tablet":[]}} -->
<div class="guten-element guten-wrap-helper no-margin guten-yTRfaH flex"><div class="guten-inner-wrap" data-id="yTRfaH"><!-- wp:gutenverse/fun-fact {"elementId":"guten-HTOYqu","iconType":"none","iconBorder":{"radius":{"Desktop":[]}},"iconPadding":{"Desktop":[]},"iconMargin":{"Desktop":[]},"prefix":"","number":"95%","suffix":"","title":"","alignButtons":{"Desktop":"center","Tablet":null},"numberColor":{"Desktop":{"type":"variable","id":"mJHk8k"}},"numberTypography":{"type":"variable","id":"FeNByJ","font":{"label":"Quicksand","value":"Quicksand","type":"google"},"size":{"Desktop":{"point":"30","unit":"px"},"Tablet":{"point":"28","unit":"px"},"Mobile":{"point":"26","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":""}},"weight":"600"},"contentPadding":{"Desktop":[]},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"positioningType":{"Desktop":"default","Tablet":"default","Mobile":"default"},"positioningWidth":{"Desktop":{"point":"401","unit":"px"}},"positioningAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"positioningLocation":"default","positioningLeft":{"Desktop":{"point":"","unit":"px"},"Tablet":{"point":"","unit":"px"}},"positioningTop":{"Desktop":{"point":"","unit":"px"},"Tablet":{"point":"","unit":"px"}}} -->
<div class="guten-element guten-HTOYqu guten-fun-fact align-center hover-from-left"><div class="fun-fact-inner"><div class="content"><div class="number-wrapper"><span class="prefix"></span><span class="number loaded" data-number="95%" data-duration="3500"></span><span class="suffix"></span></div><span class="title"></span></div></div></div>
<!-- /wp:gutenverse/fun-fact --></div></div>
<!-- /wp:gutenverse/wrapper -->

<!-- wp:gutenverse/advanced-heading {"elementId":"guten-wNKUOH","text":"","focusText":"Successful Rescue","subText":"Lorem ipsum dolor sit amet consectet adipiscing elit sedo.","showLine":"none","lineMargin":{"Desktop":[]},"mainMargin":{"Desktop":[]},"mainPadding":{"Desktop":[]},"focusColor":{"type":"variable","id":"theme-0"},"focusTypography":{"type":"variable","id":"FCF0Au","font":{"label":"Quicksand","value":"Quicksand","type":"google"},"size":{"Desktop":{"point":"22","unit":"px"},"Tablet":{"point":"21","unit":"px"},"Mobile":{"point":"20","unit":"px"}},"weight":"700","lineHeight":{"Desktop":{"unit":"em","point":"0.2"}}},"focusMargin":{"Desktop":[]},"focusPadding":{"Desktop":[]},"subColor":{"type":"variable","id":"theme-0"},"subTypography":{"type":"variable","id":"7MBQTH","font":{"label":"Quicksand","value":"Quicksand","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"15","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"unit":"em","point":"1.5"}}},"subMargin":{"Desktop":[]},"subPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","bottom":""}}}} -->
<div class="guten-element guten-advanced-heading guten-wNKUOH"><div class="heading-section "><h2 class="heading-title"><span class="heading-title"></span><span class="heading-focus">Successful Rescue</span></h2></div><span class="heading-subtitle">Lorem ipsum dolor sit amet consectet adipiscing elit sedo.</span></div>
<!-- /wp:gutenverse/advanced-heading --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":50,"Mobile":100},"elementId":"guten-86QKSs","margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"40"}},"Mobile":{"unit":"px","dimension":{"left":"0","right":"0","top":"20"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-86QKSs"><div class="guten-column-wrapper" data-id="86QKSs"><!-- wp:gutenverse/wrapper {"elementId":"guten-63wiRL","displayType":"flex","displayWidth":{"Desktop":{"point":"130","unit":"px"},"Tablet":{"point":"130","unit":"px"},"Mobile":{"point":"150","unit":"px"}},"displayHeight":{"Desktop":{"point":"130","unit":"px"},"Tablet":{"point":"130","unit":"px"},"Mobile":{"point":"150","unit":"px"}},"verticalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"background":{"type":"default","image":{"Desktop":{"id":255,"image":"https://designer.gutenverse.com/veterna/wp-content/uploads/sites/187/2025/03/82-percent.png"}},"size":{"Desktop":"custom"},"width":{"Desktop":{"point":"130","unit":"px"}},"repeat":{"Tablet":"no-repeat"},"position":{"Tablet":"center center"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"15","left":"0"}},"Tablet":{"unit":"px","dimension":{"left":""}}},"padding":{"Desktop":[],"Tablet":[]}} -->
<div class="guten-element guten-wrap-helper no-margin guten-63wiRL flex"><div class="guten-inner-wrap" data-id="63wiRL"><!-- wp:gutenverse/fun-fact {"elementId":"guten-30mbMG","iconType":"none","iconBorder":{"radius":{"Desktop":[]}},"iconBorderResponsive":{"Tablet":{"radius":[]}},"iconPadding":{"Desktop":[],"Tablet":[]},"iconMargin":{"Desktop":[],"Tablet":[]},"prefix":"","number":"82%","suffix":"","title":"","alignButtons":{"Desktop":"center"},"numberColor":{"Desktop":{"type":"variable","id":"mJHk8k"}},"numberTypography":{"type":"variable","id":"FeNByJ","font":{"label":"Quicksand","value":"Quicksand","type":"google"},"size":{"Desktop":{"point":"30","unit":"px"},"Tablet":{"point":"28","unit":"px"},"Mobile":{"point":"26","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":""}},"weight":"600"},"contentPadding":{"Desktop":[]},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":""}},"Tablet":[]},"padding":{"Desktop":[],"Tablet":[]},"positioningType":{"Desktop":"default","Tablet":"default","Mobile":"default"},"positioningWidth":{"Desktop":{"point":"401","unit":"px"}},"positioningAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"positioningLocation":"default","positioningLeft":{"Desktop":{"point":"","unit":"px"},"Tablet":{"point":"","unit":"px"}},"positioningTop":{"Desktop":{"point":"","unit":"px"},"Tablet":{"point":"","unit":"px"}}} -->
<div class="guten-element guten-30mbMG guten-fun-fact align-center hover-from-left"><div class="fun-fact-inner"><div class="content"><div class="number-wrapper"><span class="prefix"></span><span class="number loaded" data-number="82%" data-duration="3500"></span><span class="suffix"></span></div><span class="title"></span></div></div></div>
<!-- /wp:gutenverse/fun-fact --></div></div>
<!-- /wp:gutenverse/wrapper -->

<!-- wp:gutenverse/advanced-heading {"elementId":"guten-w8Pwev","text":"","focusText":"Expert Volunteer","subText":"Lorem ipsum dolor sit amet consectet adipiscing elit sedo.","showLine":"none","lineMargin":{"Desktop":[]},"mainMargin":{"Desktop":[]},"mainPadding":{"Desktop":[]},"focusColor":{"type":"variable","id":"theme-0"},"focusTypography":{"type":"variable","id":"FCF0Au","font":{"label":"Quicksand","value":"Quicksand","type":"google"},"size":{"Desktop":{"point":"22","unit":"px"},"Tablet":{"point":"21","unit":"px"},"Mobile":{"point":"20","unit":"px"}},"weight":"700","lineHeight":{"Desktop":{"unit":"em","point":"0.2"}}},"focusMargin":{"Desktop":[]},"focusPadding":{"Desktop":[]},"subColor":{"type":"variable","id":"theme-0"},"subTypography":{"type":"variable","id":"7MBQTH","font":{"label":"Quicksand","value":"Quicksand","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"15","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"unit":"em","point":"1.5"}}},"subMargin":{"Desktop":[]},"subPadding":{"Desktop":{"unit":"px","dimension":{"top":"15"}}}} -->
<div class="guten-element guten-advanced-heading guten-w8Pwev"><div class="heading-section "><h2 class="heading-title"><span class="heading-title"></span><span class="heading-focus">Expert Volunteer</span></h2></div><span class="heading-subtitle">Lorem ipsum dolor sit amet consectet adipiscing elit sedo.</span></div>
<!-- /wp:gutenverse/advanced-heading --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --><!-- wp:gutenverse/section {"width":{"Desktop":"380"},"gap":"no","elementId":"guten-Y5UEFE","margin":{"Desktop":{"unit":"px","dimension":{"top":"-80"}},"Mobile":{"unit":"px","dimension":{"top":"-80","right":"0","bottom":"0","left":"0"}},"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"100","top":""}},"Mobile":{"unit":"px","dimension":{"right":"20","left":"20","bottom":"30"}},"Tablet":{"unit":"px","dimension":{"bottom":""}}}} -->
<div class="section-wrapper" data-id="Y5UEFE"><section class="wp-block-gutenverse-section guten-element guten-section guten-Y5UEFE layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-l2hQn1","background":{"type":"default","color":{"type":"variable","id":"theme-3"}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}}},"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-l2hQn1"><div class="guten-column-wrapper" data-id="l2hQn1"><!-- wp:gutenverse/advanced-heading {"elementId":"guten-2p4FXW","text":"","focusText":"Anatole France","subText":"\u003cem\u003e\u0022Until one has loved an animal a part of one\'s soul remains unawakened.\u0022\u003c/em\u003e","showSub":"top","showLine":"none","lineMargin":{"Desktop":[]},"mainMargin":{"Desktop":[]},"mainPadding":{"Desktop":[]},"focusColor":{"type":"variable","id":"theme-4"},"focusTypography":{"type":"variable","id":"YlLg3o","font":{"label":"Quicksand","value":"Quicksand","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"17","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"weight":"700"},"focusMargin":{"Desktop":[]},"focusPadding":{"Desktop":[]},"subColor":{"type":"variable","id":"theme-4"},"subTypography":{"type":"variable","id":"mqNyw5","font":{"label":"Quicksand","value":"Quicksand","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"17","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"weight":"400"},"subMargin":{"Desktop":[]},"subPadding":{"Desktop":{"unit":"px","dimension":{"bottom":"10"}}}} -->
<div class="guten-element guten-advanced-heading guten-2p4FXW"><span class="heading-subtitle"><em>"Until one has loved an animal a part of one\'s soul remains unawakened."</em></span><div class="heading-section "><h2 class="heading-title"><span class="heading-title"></span><span class="heading-focus">Anatole France</span></h2></div></div>
<!-- /wp:gutenverse/advanced-heading --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
	'images'      => '[{"name":"bg2-freepik.webp","image_url":"https:\/\/designer.gutenverse.com\/veterna\/wp-content\/uploads\/sites\/187\/2025\/03\/bg2-freepik.webp","type":"sync","id":1140,"image_id":221},{"name":"woman-volunteer-meeting-homeless-dog-puppies-in-fall-nature-background-pet-love-caring-for-pets-e1636548359393.webp","image_url":"https:\/\/designer.gutenverse.com\/veterna\/wp-content\/uploads\/sites\/187\/2025\/03\/woman-volunteer-meeting-homeless-dog-puppies-in-fall-nature-background-pet-love-caring-for-pets-e1636548359393.webp","type":"sync","id":1140,"image_id":252},{"name":"95-percent.png","image_url":"https:\/\/designer.gutenverse.com\/veterna\/wp-content\/uploads\/sites\/187\/2025\/03\/95-percent.png","type":"sync","id":1140,"image_id":256},{"name":"82-percent.png","image_url":"https:\/\/designer.gutenverse.com\/veterna\/wp-content\/uploads\/sites\/187\/2025\/03\/82-percent.png","type":"sync","id":1140,"image_id":255}]',
	'is_sync' => true,
);
